import "~/styles/globals.css";

import { type Metadata } from "next";
import Navbar from "~/components/global/Navbar";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/components/ui/sonner";
import { Analytics } from "@vercel/analytics/next";
export const metadata: Metadata = {
    title: "GHS Computer Science UIL",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <TRPCReactProvider>
                    <Navbar />
                    <main className="bg-primary min-h-screen">{children}</main>
                </TRPCReactProvider>
                <Toaster />
                <Analytics />
            </body>
        </html>
    );
}
